export const MERCABAQ_TOKEN_SESSION: any = 'MERCABAQ_TOKEN_SESSION';
export const MERCABAQ_LOGOUT_REQUEST: any = 'MERCABAQ_LOGOUT_REQUEST';
export const MERCABAQ_FORCED_LOGOFF: any = 'MERCABAQ_FORCED_LOGOFF';
export const MERCABAQ_RESET_FORCED_LOGOFF: any = 'MERCABAQ_RESET_FORCED_LOGOFF';
export const MERCABAQ_LOGOUT_SUCCESS: any = 'MERCABAQ_LOGOUT_SUCCESS';

export const LOGIN_WITH_EMAIL_REQUEST: any = 'MERCABAQ_LOGIN_WITH_EMAIL_REQUEST';
export const LOGIN_WITH_EMAIL_SUCCESS: any = 'MERCABAQ_LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAILURE: any = 'MERCABAQ_LOGIN_WITH_EMAIL_FAILURE';
export const LOGIN_WITH_EMAIL_FAILED: any = 'MERCABAQ_LOGIN_WITH_EMAIL_FAILED';
export const PASSWORD_FORGET_REQUEST: any = 'MERCABAQ_PASSWORD_FORGET_REQUEST';
export const MERCABAQ_SIGNUP_REQUEST: any = 'MERCABAQ_MERCABAQ_SIGNUP_REQUEST';
export const LOGIN_BTN_LOADING: any = 'MERCABAQ_LOGIN_BTN_LOADING';

export const MERCABAQ_ADD_BUSINESS_DATA: any = 'MERCABAQ_ADD_BUSINESS_DATA';
