export const CART_APP_ADD_ITEM: any = 'MERCABAQ_CART_ADD_ITEM';
export const CART_APP_REMOVE_ITEM: any = 'MERCABAQ_CART_REMOVE_ITEM';
export const CART_APP_CLEAR_CART: any = 'MERCABAQ_CART_CLEAR_CART';