export const UTIL_APP_SHOW_ALERT: any = 'MERCABAQ_UTIL_APP_SHOW_ALERT';
export const UTIL_APP_HIDE_ALERT: any = 'MERCABAQ_UTIL_APP_HIDE_ALERT';

export const UTIL_APP_PROGRESS_DIALOG: any = 'MERCABAQ_UTIL_APP_PROGRESS_DIALOG';

